name: Pylint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Analyse text-to-event.py with pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pylint text-to-event --disable C0103,E1102,R1732,E0401